
version: '3.8'

services:


  wso2integration:
    depends_on: [ "wso2ei"]
    build: dockercompose/wso2integration
    ports:
      - "8080:8080"
    volumes:
      - ./dockercompose/wso2integration/app.jar:/home/app.jar


  wso2ei:
    image: wso2/wso2is:5.10.0
    ports:
      - 9443:9443
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:9443/carbon/admin/login.jsp"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 100s
    volumes:
      - ./dockercompose/cert/wso2ei.jks:/home/wso2carbon/wso2is-5.10.0/repository/resources/security/wso2ei.jks
      - ./dockercompose/wso2ei/conf/deployment.toml:/home/wso2carbon/wso2is-5.10.0/repository/conf/deployment.toml
